"""make keys as nullable in  Artifacts Schema

Revision ID: 03d697fd463a
Revises: 1013558eed03
Create Date: 2025-11-09 20:42:17.850309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d697fd463a'
down_revision: Union[str, Sequence[str], None] = '1013558eed03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifacts', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('artifacts', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artifacts', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('artifacts', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifacts', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('artifacts', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('artifacts', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artifacts', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
