"""add keys to Artifacts Schema

Revision ID: 1013558eed03
Revises: dc01f2dc07bf
Create Date: 2025-11-09 20:24:47.829844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1013558eed03'
down_revision: Union[str, Sequence[str], None] = 'dc01f2dc07bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add new columns as NULLABLE first
    op.add_column('artifacts', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('artifacts', sa.Column('file_id', sa.Integer(), nullable=True))
    op.add_column('artifacts', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('artifacts', sa.Column('file_type', sa.String(), nullable=True))

    # 2. Drop old column
    op.drop_column('artifacts', 'content_type')

    # 3. Backfill defaults if needed (placeholder values)
    # Remove this block if artifacts table is empty
    op.execute("""
        UPDATE artifacts
        SET file_id = 0,
            file_path = '',
            file_type = 'unknown'
        WHERE file_id IS NULL OR file_path IS NULL OR file_type IS NULL;
    """)

    # 4. Enforce NOT NULL
    op.alter_column('artifacts', 'file_id', nullable=False)
    op.alter_column('artifacts', 'file_path', nullable=False)
    op.alter_column('artifacts', 'file_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('artifacts', 'file_type')
    op.drop_column('artifacts', 'file_path')
    op.drop_column('artifacts', 'file_id')
    op.drop_column('artifacts', 'thumbnail_url')
    # ### end Alembic commands ###
